import { FinalPlan, Idea } from "./types";

export function generateMarkdown(plan: FinalPlan, idea: Idea): string {
  const lines: string[] = [];

  lines.push(`# ${plan.projectName}`);
  lines.push(`> ${plan.oneLiner}`);
  lines.push("");

  lines.push("## Problem");
  lines.push(plan.problem);
  lines.push("");

  lines.push("## Why This Hackathon");
  lines.push(plan.hackathonFit);
  lines.push("");

  lines.push("## Track & Sponsor Alignment");
  lines.push(`**Track:** ${plan.trackAlignment}`);
  lines.push(`**Sponsor:** ${plan.sponsorAlignment}`);
  lines.push("");

  lines.push("## User Flow");
  plan.userFlow.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
  lines.push("");

  lines.push("## MVP Features");
  plan.mvpFeatures.forEach((f) => lines.push(`- ${f}`));
  lines.push("");

  lines.push("## Stretch Features");
  plan.stretchFeatures.forEach((f) => lines.push(`- ${f}`));
  lines.push("");

  lines.push("## Cut If Behind");
  plan.cutFeatures.forEach((f) => lines.push(`- ${f}`));
  lines.push("");

  lines.push("## Architecture");
  lines.push(plan.architecture);
  lines.push("");

  lines.push("## Tech Stack");
  plan.techStack.forEach((t) => lines.push(`- ${t}`));
  lines.push("");

  lines.push("## Hour-by-Hour Timeline");
  lines.push("| Hour | Task |");
  lines.push("|------|------|");
  plan.timeline.forEach((e) => lines.push(`| ${e.hour} | ${e.task} |`));
  lines.push("");

  lines.push("## Task Breakdown");
  lines.push("### Must Do");
  plan.tasks
    .filter((t) => t.priority === "must")
    .forEach((t) => lines.push(`- [ ] ${t.label}`));
  lines.push("### Should Do");
  plan.tasks
    .filter((t) => t.priority === "should")
    .forEach((t) => lines.push(`- [ ] ${t.label}`));
  lines.push("### Stretch");
  plan.tasks
    .filter((t) => t.priority === "stretch")
    .forEach((t) => lines.push(`- [ ] ${t.label}`));
  lines.push("");

  lines.push("## Demo Script (<2 min)");
  lines.push(plan.demoScript);
  lines.push("");

  lines.push("## Pitch Script");
  lines.push(plan.pitchScript);
  lines.push("");

  lines.push("## Judging Strategy");
  lines.push(plan.judgingStrategy);
  lines.push("");

  lines.push("## Risks");
  plan.risks.forEach((r) => lines.push(`- ${r}`));
  lines.push("");

  lines.push("## Submission Checklist");
  plan.submissionChecklist.forEach((c) => lines.push(`- [ ] ${c}`));
  lines.push("");

  lines.push("---");
  lines.push(`*Win Score: ${idea.winScore}/100 · Generated by Hackathon Idea OS*`);

  return lines.join("\n");
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
